name: 'CI: Flake check'

on:
  push:
    branches:
      - main
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'treefmt.nix'
      - '.github/workflows/nix-flake.yaml'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Install Nix
        uses: cachix/install-nix-action@a49548c11d9846ad46ecc0115273879b045f001c # v31.10.7
        with:
          github_access_token: ${{ github.token }}

      - name: Check flake
        run: nix flake check --all-systems --show-trace

      - name: Build package (verify vendorHash)
        run: nix build
